name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
      - run: yarn install --frozen-lockfile

      - run: yarn ci:check
      - run: yarn ci:build
        env:
          PORT: ${{ secrets.PORT }}
      - run: yarn ci:test
